/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './index.ts', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#7E3B3B',
        'primary-dark': '#5E2B2B',
        'primary-light': '#9A5252',
        dark: '#1A140F',
        'dark-card': '#241C14',
        'dark-elevated': '#2B2118',
        'dark-border': '#3D3123',
        accent: '#B3924C',
        'accent-light': '#CDB279',
        sage: '#9BAA8D',
        rose: '#C99B8E',
        leather: '#6B5138',
        offwhite: '#F4EDE1',
        'text-secondary': '#7A6A58',
        'text-muted': '#A5947E',
        success: '#6E8B6A',
        danger: '#A65546',
        warning: '#C0913F',
      },
      fontFamily: {
        display: ['Cinzel_700Bold'],
        'display-regular': ['Cinzel_400Regular'],
        heading: ['PlayfairDisplay_700Bold'],
        'heading-regular': ['PlayfairDisplay_400Regular'],
        body: ['Inter_400Regular'],
        'body-medium': ['Inter_500Medium'],
        'body-semibold': ['Inter_600SemiBold'],
        'body-bold': ['Inter_700Bold'],
      },
    },
  },
  plugins: [],
};
